### ISSUE TITLE
nonce required in implicit grant type

### ISSUE THREAD

**Issue by eamelink** [orus-io/elm-openid-connect#1]
The OpenID Connect spec requires the use of a nonce for the implicit grant type, see http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest

But it seems to be impossible to set it with this library.

**Comment by cdevienne** [comment]
Indeed its missing. I am looking into it.

**Comment by eamelink** [comment]
I have a trivial implementation, just as an additional required parameter to `newAuth`. But something smarter might be useful since you're supposed to check the nonce after the redirect, so it should also be stored in local storage or something like that. Not sure if you'd want that in the library or external to it.

**Comment by cdevienne** [comment]
I am working on a first version that does not break the API.
Will push it soon.
